### ISSUE TITLE
Possible to share your model?

### ISSUE THREAD

**Issue by mhasnat** [liu-xb/RAM#3]
Hi,

I would like to know if it is possible to share your model. I just need it to extract features from 10K vehicle images.

Thanks.

**Comment by liu-xb** [comment]
Our models and extracted features on VeRi can be downloaded from [here.](https://pan.baidu.com/s/17fnjp1fAvWNmIrF1wzkQqg#list/path=%2F&parentPath=%2F) The model is trained on [VeRi](https://github.com/VehicleReId/VeRidataset) dataset.

**Comment by mhasnat** [comment]
Thank you for indicating the link. Unfortunately, I am unable to download from baidu. Is it possible to provide alternative links, such as good-drive or dropbox?

Thanks.

**Comment by liu-xb** [comment]
Please check this [link](https://drive.google.com/open?id=1CekbI5jHgq8YJw03pfhBNQefnXCmdOZn) from google drive.

**Comment by mhasnat** [comment]
Thank you so much for sharing it.
