### ISSUE TITLE
How can I train on VehicleID?

### ISSUE THREAD

**Issue by hqulxw123** [liu-xb/RAM#4]
I just started to study Vehicle Re-ID. It is convenient to tell me how to train on VehicleID. Thank you very much! ! ! Looking forward to your reply! ! !

**Comment by liu-xb** [comment]
Please kindly clarify your question. What do you want to know about training on VehicleID? If you just want to train our model on VehicleID dataset, you can just replace the paths of the dataset with your own ones.

**Comment by liu-xb** [comment]
As no more question for about 3 months, I closed the issue. And you can open another issue anytime if you have any other question.
